id: I9A861F08
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:08:13+00:00'
last_modified: '2022-06-08T09:53:26.378587+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21699
  title: བརྩེ་དུང་གི་མིག་ཆུ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CD64:
      image_group_id: I1KG22929
      title: ''
      total_pages: 412
      order: 1
      base_file: CD64.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
