id: P006989
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W21699
  title: བརྩེ་དུང་གི་མིག་ཆུ།
  author: ''
  volumes:
    c6e12e87e91e42a68ea6f59d0cfba163:
      image_group_id: I1KG22929
      title: ''
      volume_number: 1
      total_pages: 412
